# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

edition = "2021"
error_on_line_overflow = true
error_on_unformatted = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
newline_style = "Unix"
overflow_delimited_expr = true
use_field_init_shorthand = true
version = "Two"
wrap_comments = true
